# Generated by Django 4.2.14 on 2024-07-27 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='read',
            new_name='sent',
        ),
        migrations.AddField(
            model_name='notification',
            name='recipient_type',
            field=models.CharField(choices=[('vendor', 'Vendor'), ('customer', 'Customer')], default='3x', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notification',
            name='relevant',
            field=models.BooleanField(default=True),
        ),
    ]
