# Generated by Django 4.0.10 on 2024-06-02 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_vendorauth_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendorauth',
            name='user',
        ),
    ]
