# Generated by Django 4.0.10 on 2024-06-02 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_vendorauth_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VendorLocation',
        ),
    ]
