# Generated by Django 4.0.10 on 2024-06-02 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_delete_vendorlocation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendorauth',
            name='user',
        ),
    ]
