# Generated by Django 4.0.10 on 2024-06-02 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_vendorauth_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('vendor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.vendorauth')),
            ],
        ),
    ]
