# Generated by Django 4.0.10 on 2024-06-02 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_remove_vendorlocation_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendorlocation',
            name='vendor',
        ),
    ]
