# Generated by Django 4.0.10 on 2024-06-02 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_vendorauth_user_vendorlocation_vendor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendorauth',
            name='user',
        ),
    ]
