# Generated by Django 4.0.10 on 2024-06-02 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_remove_vendorauth_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorlocation',
            name='vendor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='location', to='api.vendorauth'),
        ),
    ]
