from django.test import TestCase
from rest_framework_simplejwt.tokens import AccessToken

# Create your tests here.
acc = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzIwMjkwMzE5LCJpYXQiOjE3MjAyOTAwMTksImp0aSI6IjFkZmY3ZTkzZDdmOTQ0ODRhYTViMzNmYWRhYjAxZTYzIiwidXNlcl9pZCI6NX0.gcCAZGSg6tbzpUq1BUruvjU_0u4N3N7yz8tkpHcM9Vs"
token = AccessToken("eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzIwMjkwODcxLCJpYXQiOjE3MjAyOTA1NzEsImp0aSI6ImJlODJjMzE4MzZlYzQ1MmE4MDk0OTNlZGQyMTZkOTk1IiwidXNlcl9pZCI6Nn0._fLNJIqJqLzrjigRXCwZgZorFPlYtd3V6cshq2BtgP0")
print(token.payload)
print(token.is_valid())